# Generated by Django 5.0.4 on 2024-05-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_verificate_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificate',
            name='is_verficate',
        ),
        migrations.AddField(
            model_name='verificate',
            name='is_verificate',
            field=models.BooleanField(default=False),
        ),
    ]
