# Generated by Django 5.0.4 on 2024-06-01 15:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_verificate_is_verficate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificate',
            name='verification_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
